name: Run prettier check

on: [push]
    
jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install prettier

      - name: Run Prettier Check
        run: npx prettier --check "**/*.{ts,tsx}"
